INSERT INTO tb_category(name) VALUES('Books');
INSERT INTO tb_category(name) VALUES('Electronics');
INSERT INTO tb_category(name) VALUES('Fashion');
INSERT INTO tb_category(name) VALUES('Home & Kitchen');
INSERT INTO tb_category(name) VALUES('Sports & Outdoors');
INSERT INTO tb_category(name) VALUES('Toys & Games');
INSERT INTO tb_category(name) VALUES('Baby Products');
INSERT INTO tb_category(name) VALUES('Pet Supplies');
INSERT INTO tb_category(name) VALUES('Health & Personal Care');
INSERT INTO tb_category(name) VALUES('Beauty & Personal Care');
INSERT INTO tb_category(name) VALUES('Grocery & Gourmet Food');
INSERT INTO tb_category(name) VALUES('Automotive');
INSERT INTO tb_category(name) VALUES('Arts, Crafts & Sewing');
INSERT INTO tb_category(name) VALUES('Office Products');
INSERT INTO tb_category(name) VALUES('Industrial & Scientific');
INSERT INTO tb_category(name) VALUES('Musical Instruments');
INSERT INTO tb_category(name) VALUES('Handmade Products');
INSERT INTO tb_category(name) VALUES('Digital Music');
INSERT INTO tb_category(name) VALUES('Prime Video');
INSERT INTO tb_category(name) VALUES('Software');
INSERT INTO tb_category(name) VALUES('Video Games');
INSERT INTO tb_category(name) VALUES('Wine');
INSERT INTO tb_category(name) VALUES('Furniture');
INSERT INTO tb_category(name) VALUES('Tools & Home Improvement');
INSERT INTO tb_category(name) VALUES('Patio, Lawn & Garden');
INSERT INTO tb_category(name) VALUES('Kitchen & Dining');
INSERT INTO tb_category(name) VALUES('Bed & Bath');
INSERT INTO tb_category(name) VALUES('Appliances');
INSERT INTO tb_category(name) VALUES('Lighting & Ceiling Fans');
INSERT INTO tb_category(name) VALUES('Bath & Shower');
INSERT INTO tb_category(name) VALUES('Decor & Pillows');
INSERT INTO tb_category(name) VALUES('Wall Art');
INSERT INTO tb_category(name) VALUES('Rugs');
INSERT INTO tb_category(name) VALUES('Window Treatments');
INSERT INTO tb_category(name) VALUES('Storage & Organization');
INSERT INTO tb_category(name) VALUES('Fireplaces & Accessories');
INSERT INTO tb_category(name) VALUES('Heating, Cooling & Air Quality');
INSERT INTO tb_category(name) VALUES('Smart Home Devices');
INSERT INTO tb_category(name) VALUES('Security Systems');
INSERT INTO tb_category(name) VALUES('Home Security Cameras');
INSERT INTO tb_category(name) VALUES('Door Hardware');
INSERT INTO tb_category(name) VALUES('Building Materials');
INSERT INTO tb_category(name) VALUES('Power & Hand Tools');
INSERT INTO tb_category(name) VALUES('Ladders & Scaffolding');
INSERT INTO tb_category(name) VALUES('Painting Supplies');
INSERT INTO tb_category(name) VALUES('Adhesives & Sealants');
INSERT INTO tb_category(name) VALUES('Fasteners & Hardware');
INSERT INTO tb_category(name) VALUES('Welding & Soldering');
INSERT INTO tb_category(name) VALUES('Automotive Tools & Equipment');
INSERT INTO tb_category(name) VALUES('Automotive Parts & Accessories');